"""The golden run-artifact corpus: real bayesite runs, committed as fixtures.

These artifacts are generated by ``scripts/generate_artifact_corpus.py`` with
a real bayesite binary and consumed by downstream exporters (bayesite_idata)
as test fixtures. This test validates their committed shape with the standard
library only; it does not re-run any engine.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from bayeswire.ir import meta_from_dict, model_data_fingerprint

ARTIFACT_DIR = Path(__file__).parent.parent.parent / "src" / "bayeswire" / "corpus" / "artifacts"
ARTIFACT_MODELS = ("eight_schools_non_centered", "varying_intercepts_poisson")


def _case_ids() -> list[str]:
    return list(ARTIFACT_MODELS)


@pytest.mark.parametrize("name", ARTIFACT_MODELS, ids=_case_ids())
def test_artifact_run_directory_is_complete(name: str) -> None:
    run_dir = ARTIFACT_DIR / name

    for artifact in ("model.ir.json", "data.json", "posterior.ndjson", "diagnostics.json"):
        assert (run_dir / artifact).is_file(), f"{name} is missing {artifact}"


@pytest.mark.parametrize("name", ARTIFACT_MODELS, ids=_case_ids())
def test_artifact_model_document_is_the_corpus_model(name: str) -> None:
    run_dir = ARTIFACT_DIR / name
    corpus_document = json.loads((ARTIFACT_DIR.parent / f"{name}.json").read_text(encoding="utf-8"))

    document = json.loads((run_dir / "model.ir.json").read_text(encoding="utf-8"))

    assert document["bayeswire_ir"] == 1
    assert meta_from_dict(document) == meta_from_dict(corpus_document)


@pytest.mark.parametrize("name", ARTIFACT_MODELS, ids=_case_ids())
def test_artifact_posterior_stream_is_per_draw_v2(name: str) -> None:
    run_dir = ARTIFACT_DIR / name
    manifest = json.loads((run_dir / "manifest.json").read_text(encoding="utf-8"))

    lines = (run_dir / "posterior.ndjson").read_text(encoding="utf-8").splitlines()
    header = json.loads(lines[0])

    assert header["sample_stats_mode"] == "per_draw_v2"
    assert manifest["sample_stats_mode"] == "per_draw_v2"
    assert header["chain_count"] == manifest["chains"]
    expected_draws = manifest["chains"] * manifest["draws"]
    assert header["draw_count"] == expected_draws
    draw_lines = [json.loads(line) for line in lines[1:] if line.strip()]
    values_lines = [line for line in draw_lines if "values" in line]
    assert len(values_lines) == expected_draws


@pytest.mark.parametrize("name", ARTIFACT_MODELS, ids=_case_ids())
def test_artifact_data_document_is_canonical_wrapped(name: str) -> None:
    run_dir = ARTIFACT_DIR / name

    document = json.loads((run_dir / "data.json").read_text(encoding="utf-8"))

    assert document["format"] == "bayescycle.data.json.v1"
    assert isinstance(document["variables"], dict)
    assert document["variables"], f"{name} data.json carries no variables"


@pytest.mark.parametrize("name", ARTIFACT_MODELS, ids=_case_ids())
def test_artifact_fit_fingerprint_matches_the_run_files(name: str) -> None:
    run_dir = ARTIFACT_DIR / name
    expected = model_data_fingerprint(
        (run_dir / "model.ir.json").read_bytes(),
        (run_dir / "data.json").read_bytes(),
    )

    lines = (run_dir / "posterior.ndjson").read_text(encoding="utf-8").splitlines()
    header = json.loads(lines[0])
    trailer = json.loads(lines[-1])["trailer"]

    assert header["model_data_fingerprint"] == expected
    assert trailer["model_data_fingerprint"] == expected


@pytest.mark.parametrize("name", ARTIFACT_MODELS, ids=_case_ids())
def test_artifact_diagnostics_parse(name: str) -> None:
    run_dir = ARTIFACT_DIR / name

    diagnostics = json.loads((run_dir / "diagnostics.json").read_text(encoding="utf-8"))

    assert diagnostics, f"{name} diagnostics.json must be non-empty"


def test_dims_sidecar_travels_with_the_labeled_model() -> None:
    document = json.loads(
        (ARTIFACT_DIR / "eight_schools_non_centered" / "dims.json").read_text(encoding="utf-8")
    )

    assert document["dims_format"] == "bayescycle-dims-v1"
    assert document["dims"]["y"] == ["school"]
    assert document["dims"]["z"] == ["school"]
    assert document["coords"]["school"] == ["A", "B", "C", "D", "E", "F", "G", "H"]
